name: attedly_kiosk
description: Multi-tenant kiosk attendance Flutter app for Attedly.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  supabase_flutter: ^2.1.3
  http: ^0.13.6
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.12
  sqflite: ^2.3.3
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_face_mesh: ^0.3.0
  permission_handler: ^11.1.0
  camera: ^0.10.5+7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  collection: ^1.18.0
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.4.3
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilefacenet.tflite
    - assets/prompts/
